import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  maincontainer: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: 'white',
  },
  backbtn: {
    width: 42,
    marginLeft: '5%',
  },
  modalcontainer: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: 'rgba(255, 255, 255, 0.97)',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: '15%',
    paddingHorizontal: '10%',
  },
  image: {
    width: 200,
    height: 200,
  },
  textmodal: {
    fontFamily: 'Kanit-Medium',
    fontSize: 18,
    color: '#5784BA',
  },
  content: {
    flex: 1,
    flexDirection: 'column',
  },
  header: {
    alignSelf: 'center',
    marginTop: '2%',
    fontFamily: 'Kanit-Medium',
    fontSize: 28,
  },
  desc1: {
    marginHorizontal: '10%',
    marginTop: '20%',
    fontFamily: 'Kanit-Medium',
    fontSize: 20,
    textAlign: 'center',
    marginBottom: '15%',
    color: 'black',
  },
  input: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: '10%',
  },
  inputlabel: {
    position: 'absolute',
    justifyContent: 'center',
    backgroundColor: 'white',
    color: '#ADA9BB',
    fontFamily: 'Kanit-Regular',
    left: 8,
    top: -10,
    paddingLeft: 2,
    paddingRight: 2,
    zIndex: 10,
  },
  textInputPassword: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ADA9BB',
    borderRadius: 10,
    padding: 10,
    fontFamily: 'Roboto-Regular',
    fontSize: 20,
    color: 'black',
  },
  warning: {
    marginTop: '2%',
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    marginHorizontal: '10%',
  },
  inputwarning: {
    marginHorizontal: '12%',
    fontFamily: 'Roboto-Medium',
    fontSize: 12,
    color: 'rgba(255, 91, 55, 1)',
  },
  warninglogo: {
    marginLeft: '2%',
  },
  input2: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: '10%',
    marginRight: '10%',
  },
  textInputrepeatPassword: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ADA9BB',
    borderRadius: 10,
    padding: 10,
    fontFamily: 'Roboto-Regular',
    fontSize: 20,
    color: 'black',
  },
  eye: {
    position: 'absolute',
    right: 15,
    justifyContent: 'center',
  },
  btnsend: {
    width: '100%',
    alignItems: 'center',
    backgroundColor: '#5784BA',
    justifyContent: 'center',
    alignSelf: 'center',
    height: 50,
    borderRadius: 10,
    padding: 10,
  },
  btntextsend: {
    fontSize: 18,
    width: '100%',
    color: 'white',
    textAlign: 'center',
    fontFamily: 'Kanit-Medium',
  },
});

export default styles;
