import {StyleSheet, Dimensions} from 'react-native';
import {getStatusBarHeight} from 'react-native-status-bar-height';

const classes = StyleSheet.create({
  container: {
    paddingHorizontal: 8,
    paddingVertical: 16,
  },
  section: {
    fontFamily: 'Montserrat-Bold',
    fontSize: 18,
  },
  heading: {
    flexDirection: 'row',
    marginBottom: 17,
    paddingHorizontal: 5,
  },
  headmyclass: {
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 16,
    marginTop: 16,
    width: '48%',
  },
  headprogress: {
    textAlign: 'center',
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 16,
    marginTop: 16,
    width: '22%',
  },
  headscore: {
    textAlign: 'center',
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 16,
    marginTop: 16,
    width: '25%',
  },
  myclass: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    margin: 2,
    borderRadius: 10,
    padding: 10,
    alignItems: 'center',
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 2,
  },

  tableclassname: {
    width: '55%',
    fontFamily: 'Montserrat-Medium',
    fontSize: 13,
  },
  tableprogress: {
    width: '25%',
  },
  textprogress: {
    color: '#5784BA',
    fontFamily: 'Montserrat-Medium',
    fontSize: 10,
  },
  tablescore: {
    width: '20%',
    fontFamily: 'Montserrat-Bold',
    fontSize: 20,
  },
  allmyclass: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 13,
  },
  textallmyclass: {
    fontFamily: 'Montserrat-Medium',
    fontSize: 14,
  },
  newClassItem: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    margin: 2,
    borderRadius: 10,
    padding: 10,
    height: 65,
    alignItems: 'center',
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 2,
  },
  headname: {
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 16,
    marginTop: 16,
    width: '39%',
  },
  headlevel: {
    textAlign: 'center',
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 16,
    marginTop: 16,
    width: '21%',
  },
  headprice: {
    textAlign: 'center',
    fontFamily: 'Montserrat-SemiBold',
    fontSize: 16,
    marginTop: 16,
    width: '18%',
  },
  newClassSection: {
    marginTop: 12,
    backgroundColor: '#FFFFFF',
    padding: 8,
    borderRadius: 10,
    paddingVertical: 25,
  },
  searchSection: {
    flexDirection: 'row',
  },
  searchInputContainer: {
    marginTop: 12,
    marginBottom: 2,
    borderColor: 'black',
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 10,
    height: 45,
    width: '75%',
  },
  searchInput: {
    fontFamily: 'Montserrat-Medium',
    color: '#ADA9A9',
    fontSize: 14,
  },
  btnSearch: {
    width: '25%',
    borderRadius: 10,
    height: 45,
    justifyContent: 'center',
    marginTop: 12,
    backgroundColor: '#5784BA',
  },
  filterSection: {
    backgroundColor: '#EEEEEE',
    borderBottomStartRadius: 10,
    borderBottomEndRadius: 10,
    flexDirection: 'row',
    height: 40,
    overflow: 'hidden',
    marginBottom: 12,
  },
  pickeritem: {fontFamily: 'Roboto-Regular', fontSize: 15},
  newClassName: {
    width: '39%',
    fontFamily: 'Montserrat-Medium',
    fontSize: 13,
  },
  newlevel: {
    textAlign: 'center',
    width: '21%',
    fontFamily: 'Montserrat-Medium',
    fontSize: 13,
  },
  newprice: {
    textAlign: 'center',
    width: '18%',
    fontFamily: 'Montserrat-Medium',
    fontSize: 13,
  },
  newbtnregister: {
    alignSelf: 'center',
    justifyContent: 'center',
    width: '22%',
    backgroundColor: '#57BA61',
    borderRadius: 16,
    height: 32,
  },
  txtRegister: {
    textAlign: 'center',
    paddingHorizontal: 5,
    fontFamily: 'Montserrat-Medium',
    fontSize: 13,
    color: 'white',
  },
  loadMore: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 12,
  },
  load: {
    alignSelf: 'center',
    marginTop: 16,
    color: '#ADA9A9',
  },
  loadarrow: {
    alignSelf: 'center',
    marginTop: -6,
  },
});
export default classes;
